var GAME_LEVELS = [
  ["                                                                                ",
   "                                           |                                    ",
   "                                           |                                    ",
   "                                           |                                    ",
   "                                           |                                    ",
   "                                           |                                    ",
   "                                           |                                    ",
   "                                                                                ",
   "                                                                 x              ",
   "           x                                |                    x              ",
   "           |          o                     d                    x              ",
   "           |         x! ! !                 d                 !  x              ",
   "  xx       |      ox ! ! !           ooo    d               !    x              ",
   "  x     b  d   o x! ! ! !           xxxx    d             !      x              ",
   "  x        d o x ! ! ! !       !   !        d xxxxx     !        x              ",
   "  x        d x! ! ! ! !      !  ooo  !      d         !     b     x              ",
   "  x  @     d x ! ! ! !        !     !       d       !     ooo    x              ",
   "  xxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxx              ",
   "                                        x     x      x     x                    ",
   "                                         xxxxx       x!!!!!x                    ",
   "                                                     x!!!!!x                    ",
   "                                                     xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                 x",
   "                                                 x",
   "                                                 x",
   "                                                 x",        
   "                                    o            x",
   "                                    x        !   x",
   "                             o      x    o!      x",
   "                        o    x      x!  !        x",
   "                        x           x!           x",
   "                                    x !          x",
   "                            o       x !          x",
   "                            x       x !  o!      x",
   "                               x    x      !     x",
   "                        o     o x   x       !    x",
   "     @             o    x       x   x   !      ! x",
   "    xxx      o     x            x   x   bo!      x",
   "    x x      x         x       xx!!!xx   xxxx    x",
   "!!!!x x!!!!!!x         x!!!!!!xx!!!!!xx!!!!!!!!xxx",
   "!!!!x x!!!!!!x         x!!!!!xx!!!!!!! xxxxxxxxxxx",
   "!!!!x x!!!!!!x         x!!!!!x !!!!!!!!!!!!!!!!!!x",
   "!!!!x x!!!!!!x         x!!!!!x!!!!!!!!!!!!!!!!!!!x",
   "!!!!x x!!!!!!x         x!!!!!xx!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                           ",
   "             @    x",
   "             o    x",
   "             o    x",
   "             o    x",
   "            o     x",
   "            o     x",
   "            o     x",
   "            o     x",
   "            o     x",
   "                  x",
   "                  x",
   "             o    x",
   "             o    x",
   "                  x",
   "            o     x",
   "            o     x",
   "                  x",
   "                  x",
   "                  x",
   "                  x",
   "            o     x",
   "                  x",
   "            o     x",
   "                  x",
   "                  x",
   "             o    x",
   "                  x",
   "                  x",
   "             o    x",
   "                  x",
   "             o    x",
   "                  x",
   "  xxx        o    x",
   "  x x             x",
   "  x               x",
   "  x               x",
   "  x               x",
   "  x               x",
   "  x               x",
   "  x               x",
   "  x               x",
   "  x           b   x",
   "  x !!        o   x",
   "  xxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                     x              x        x       xx        x    x                                         ",
   "                     x              x        x       x  x      x    x                                         ",
   "                     x     x x      x        x       x   x     x    x                                         ",
   "                     x    x   x     x        x       x     x   x                                              ",
   "                      x x       x x          x       x       x x    x                                         ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x  @                                                                                                        ",
   "  xxxxxxx                                                            d                                         ",
   "        x           ooooooooooooooooooooooooooooooooooooooooooooooooooo                                       ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
